"""empty message

Revision ID: 14131f06e80c
Revises: 1426c1b42700
Create Date: 2016-08-09 10:57:24.839533

"""

# revision identifiers, used by Alembic.
revision = '14131f06e80c'
down_revision = '1426c1b42700'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
