"""empty message

Revision ID: 1c9f1c3d58be
Revises: 14131f06e80c
Create Date: 2016-08-09 14:05:10.048224

"""

# revision identifiers, used by Alembic.
revision = '1c9f1c3d58be'
down_revision = '14131f06e80c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
