"""initial migration

Revision ID: 1ff9d055400e
Revises: None
Create Date: 2016-08-08 16:25:54.314420

"""

# revision identifiers, used by Alembic.
revision = '1ff9d055400e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
