"""empty message

Revision ID: 3347c7618689
Revises: 1c9f1c3d58be
Create Date: 2016-08-09 15:08:44.065450

"""

# revision identifiers, used by Alembic.
revision = '3347c7618689'
down_revision = '1c9f1c3d58be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
