"""empty message

Revision ID: ee5af61b38f
Revises: 3fb3b2a0a8c5
Create Date: 2016-08-10 12:52:51.180461

"""

# revision identifiers, used by Alembic.
revision = 'ee5af61b38f'
down_revision = '3fb3b2a0a8c5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
